### PR TITLE
Calendar page

### PR DESCRIPTION
**Pull request by maitmd**
- Finished loading events from database just need the notes schema and I can finish that up.
- Removed a lot of debugging stuff
- Fixed all(?) /notesbook to /notes

### CODE REVIEW

**Comment by maitmd** [comment]
I still need to implement the userName pass into the URL. Do we want to create a user ID for everyone and pass that instead for better security? Wasn't sure how we wanted to handle it so I kept mine as sessionStorage for now.

**Review by tarunJeevan — APPROVED** [review]
Looks good. I'll let you know once I've got the get notes and save notes requests set up and we can work on integrating them into the calendar

**Comment by maitmd** [comment]
> Looks good. I'll let you know once I've got the get notes and save notes requests set up and we can work on integrating them into the calendar

Sounds good. Pretty much I just need it to fill the drop-down menu and in case the user wants to save the event as a note

**Comment by kaylebredner** [comment]
> I still need to implement the userName pass into the URL. Do we want to create a user ID for everyone and pass that instead for better security? Wasn't sure how we wanted to handle it so I kept mine as sessionStorage for now.

I think just using the user name is fine, if you call the isAuthenticated function itll determine if the user is authenticated based on if they've logged in in the last hour, that should be fine for security

**Review by kaylebredner — APPROVED** [review]

**Review by AlexBishop01 — APPROVED** [review]

**Pull request merged**
