### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by maitmd**
Got Express setup to send the correct pages and all corresponding assets. There are some changes in this where I'm adding functionality to the "+" aka the add event button in the calendar page. Working on the correct branch for that now, will make a pull request when it's completed

### CODE REVIEW

**Review by tarunJeevan — COMMENTED** [review]
Server file looks great!
Is this much authentication enough though? What happens if a user navigates directly to '/calendar' or '/notes' or something without logging in first?

**Comment by maitmd** [comment]
> Server file looks great! Is this much authentication enough though? What happens if a user navigates directly to '/calendar' or '/notes' or something without logging in first?

I hadn't thought about that. I'll add comments to check for authentication on that branch. Essentially I'll have it so it checks if they are authenticated or not and if not it'll redirect to the root again (which throws them to the dashboard or login)

**Review by kaylebredner — APPROVED** [review]
looks good to me as long as the requests being made to actually login and sign up are post requests

**Comment by maitmd** [comment]
> looks good to me as long as the requests being made to actually login and sign up are post requests

I'll continue to work on more specific stuff. This was mainly just to get pages loaded so we'll need to start working on individual page requests (login validation, sign up stuff, sending notes to db, etc)

**Comment by maitmd** [comment]
> > > looks good to me as long as the requests being made to actually login and sign up are post requests
> > 
> > 
> > I'll continue to work on more specific stuff. This was mainly just to get pages loaded so we'll need to start working on individual page requests (login validation, sign up stuff, sending notes to db, etc)
> 
> I'd like to write the login authentication endpoint if that's alright, I'll work on getting login finished after this gets merged

Thatd be perfect definitely would prefer if we all worked on our own page requests to lessen confusion

**Comment by maitmd** [comment]
@tarunJeevan Pushed the super super basic auth check. Will need to update it to actually checked once we get accounts setup.

**Review by tarunJeevan — APPROVED** [review]
Looks good for now. It's not like I have much experience with authentication stuff anyway. Great job!

**Review by AlexBishop01 — APPROVED** [review]

**Pull request merged**
